export const projects = [
  {
    id: "project1",
    title: "Portfolio Webseite",
    description:
      "Meine Portfolio-Webseite mit allen meinen Projekten und Skills und mit funktionierbarm Kontakformular.",
    imageUrl: "https://i.imgur.com/7Bnn7B9.png",
    images: [
      "https://i.imgur.com/IvdoND0.png",
      "https://i.imgur.com/AelwhLw.png",
      "https://i.imgur.com/taH2fNN.png",
      "https://i.imgur.com/ga59OwL.png",
    ],
    startDate: "07.2023",
    endDate: "08.2023",
    link: "https://www.alirezarastineh.me/",
    githubUrl: "https://github.com/alirezarastineh/portfolio",
  },
  {
    id: "project2",
    title: "Rick & Morty",
    description:
      "Eine Webseite mit Rick & Morty API und deren GraphQL. Inklusive Episodes, Character & Locations Seiten.",
    imageUrl: "https://i.imgur.com/KJejjVc.png",
    images: [
      "https://i.imgur.com/IvdoND0.png",
      "https://i.imgur.com/AelwhLw.png",
      "https://i.imgur.com/9fLytGz.png",
      "https://i.imgur.com/7Cq9Dsl.png",
      "https://i.imgur.com/9hO5BKj.png",
    ],
    startDate: "07.2023",
    link: "https://rick-and-morty-next-gql.vercel.app/",
    githubUrl: "https://github.com/alirezarastineh/rick-and-morty-next-gql",
  },
  {
    id: "project3",
    title: "AlirezaBaba",
    description:
      "THE MERN-Stack Projekt!  Eine Amazon-ähnliche Einkaufswebsite zum Kauf von Autos. Inklusive Autorisierung, Admin-Dashboard, echte PayPal-Zahlung und vieles mehr.",
    imageUrl: "https://i.imgur.com/9isIWkx.png",
    images: [
      "https://i.imgur.com/IvdoND0.png",
      "https://i.imgur.com/Eonjo5f.png",
      "https://i.imgur.com/6bxEQ9s.png",
      "https://i.imgur.com/F4QkDAV.png",
      "https://i.imgur.com/E2gonVz.png",
      "https://i.imgur.com/LqZKvdX.png",
    ],
    startDate: "06.2023",
    endDate: "07.2023",
    link: "https://alireza-baba.vercel.app/",
    githubUrl: "https://github.com/alirezarastineh/AlirezaBaba",
  },
  {
    id: "project4",
    title: "Cryptocurrency Club",
    description:
      "Eine Webseite zur Überprüfung der Top 10 Kryptowährungs mit ihren Echtzeit-Statistiken. Sie beinhaltet eine Authentifizierung mit der Option, dass Benutzer Coins für ihre Wish List auswählen können.",
    imageUrl: "https://i.imgur.com/o07EM5S.png",
    images: [
      "https://i.imgur.com/UZMww1q.png",
      "https://i.imgur.com/Jx7gRFU.png",
      "https://i.imgur.com/taH2fNN.png",
      "https://i.imgur.com/UjFAGog.png",
      "https://i.imgur.com/9hO5BKj.png",
    ],
    startDate: "04.2023",
    endDate: "05.2023",
    link: "https://cryptocurrency-club.vercel.app/",
    githubUrl: "https://github.com/alirezarastineh/Crypto-Project",
  },
  {
    id: "project5",
    title: "Rick & Morty",
    description:
      "Eine Webseite mit Rick & Morty API. Inklusive Suchfunktion für jede Character.",
    imageUrl: "https://i.imgur.com/ZCOlSum.png",
    images: [
      "https://i.imgur.com/UZMww1q.png",
      "https://i.imgur.com/Jx7gRFU.png",
      "https://i.imgur.com/6bxEQ9s.png",
      "https://i.imgur.com/9hO5BKj.png",
    ],
    startDate: "04.2023",
    link: "https://rick-and-morty-simple.vercel.app/",
    githubUrl: "https://github.com/alirezarastineh/Rick-And-Morty-Mini-Project",
  },
  {
    id: "project6",
    title: "Cryptocurrency Club",
    description:
      "Eine Webseite zur Überprüfung der Top 100 Kryptowährungs mit ihren Echtzeit-Statistiken, Aktuellste Krypto-Nachrichten. Inklusive Kontakt und Registration Seiten.",
    imageUrl: "https://i.imgur.com/djMATJZ.png",
    images: [
      "https://i.imgur.com/b0f0L7E.png",
      "https://i.imgur.com/lmNHoXw.png",
      "https://i.imgur.com/UZMww1q.png",
      "https://i.imgur.com/9hO5BKj.png",
    ],
    startDate: "03.2023",
    endDate: "04.2023",
    link: "https://cryptocurrency-club-simple.vercel.app/",
    githubUrl: "https://github.com/alirezarastineh/Cryptocurrency-Project",
  },
];
